
server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://test2:12345@localhost:20000/test?authMechanism=SCRAM-SHA-256

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: test
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
    #?? ???. ?? ?? ???? ????.. ?? ??? ???????
    #?? ???? ???? ?? ????
    #??? ????? ??? ?? ????...